CC=g++
CFLAGS=-c -Wall `sdl2-config --cflags`
LDFLAGS=`sdl2-config --libs` -lSDL2_image -lraspicam
SOURCES=main.cpp util.cpp main_phototwix.cpp screen.cpp screen_camera.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=phototwix

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@
